version: "3"

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command:
      - --config=/etc/otel-collector.yaml
      - --feature-gates=pkg.translator.prometheus.NormalizeName
    volumes:
      - ./o11y/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4317:4317" # otlp http
      - "4318:4318" # otlp http
      - "55679:55679" # zpages

  tempo:
    image: grafana/tempo:latest
    command:
      - -config.file=/etc/tempo.yaml
    volumes:
      - ./o11y/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    ports:
      - "4300:4317" # otlp grpc

  loki:
    image: grafana/loki:latest
    command:
      - -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./o11y/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./o11y/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"

volumes:
  tempo-data:
